import { prisma } from "@/lib/prisma";
import { businessDaysBetween } from "@/lib/business-days";
import type { NotificationType } from "@prisma/client";

type NotificationInput = {
  userId: string;
  type: NotificationType;
  message: string;
  link?: string;
  entityType?: string;
  entityId?: string;
  dedupeKey: string;
};

async function pushNotifications(items: NotificationInput[]) {
  if (items.length === 0) return;
  await prisma.notification.createMany({ data: items, skipDuplicates: true });
}

async function allUserIds(): Promise<string[]> {
  const users = await prisma.user.findMany({ select: { id: true } });
  return users.map((u) => u.id);
}

async function managerUserIds(): Promise<string[]> {
  const users = await prisma.user.findMany({
    where: { role: "MANAGER" },
    select: { id: true },
  });
  return users.map((u) => u.id);
}

// --- Rule 1 & the FEEDBACK_OVERDUE auto-ticket ------------------------------

async function checkFeedbackOverdue(now: Date) {
  const candidates = await prisma.candidate.findMany({
    where: {
      lastSubmittedAt: { not: null },
      stage: { notIn: ["HIRED", "REJECTED"] },
    },
    include: {
      notes: { orderBy: { createdAt: "desc" }, take: 1 },
      role: { include: { company: true } },
      tickets: { where: { type: "FEEDBACK_OVERDUE" } },
    },
  });

  const notifications: NotificationInput[] = [];

  for (const c of candidates) {
    const submittedAt = c.lastSubmittedAt!;
    // Stage hasn't moved since submission, and no note logged since submission.
    const stageMovedSinceSubmission = c.stageChangedAt > submittedAt;
    const latestNote = c.notes[0];
    const notedSinceSubmission = latestNote && latestNote.createdAt > submittedAt;
    if (stageMovedSinceSubmission || notedSinceSubmission) continue;

    if (businessDaysBetween(submittedAt, now) < 2) continue;
    if (!c.assignedRecruiterId) continue;

    const dedupeKey = `feedback-overdue-${c.id}-${submittedAt.toISOString()}`;

    notifications.push({
      userId: c.assignedRecruiterId,
      type: "FEEDBACK_OVERDUE",
      message: `Feedback overdue on ${c.name} (${c.role.company.name}) — submitted ${businessDaysBetween(
        submittedAt,
        now
      )} business days ago with no update.`,
      link: `/candidates/${c.id}`,
      entityType: "Candidate",
      entityId: c.id,
      dedupeKey,
    });

    const alreadyTicketed = c.tickets.some((t) => t.createdAt > submittedAt);
    if (!alreadyTicketed) {
      await prisma.ticket.create({
        data: {
          companyId: c.role.companyId,
          candidateId: c.id,
          subject: `Feedback overdue: ${c.name} at ${c.role.company.name}`,
          description:
            "Auto-generated: this candidate's stage hasn't moved and no note has been logged within 2 business days of client submission.",
          type: "FEEDBACK_OVERDUE",
          autoGenerated: true,
          priorityConfirmed: false,
          priority: "MEDIUM",
          assignedToId: c.assignedRecruiterId,
        },
      });
    }
  }

  await pushNotifications(notifications);
}

// --- Guarantee-triggered replacement ticket ---------------------------------

async function checkGuaranteeTriggers() {
  const placements = await prisma.placement.findMany({
    where: {
      status: { in: ["ENDED", "TERMINATED"] },
      endDate: { not: null },
    },
    include: {
      candidate: true,
      company: true,
      role: true,
      tickets: { where: { type: "GUARANTEE_REPLACEMENT" } },
    },
  });

  for (const p of placements) {
    if (p.tickets.length > 0) continue;
    const daysActive = Math.floor(
      (p.endDate!.getTime() - p.startDate.getTime()) / (1000 * 60 * 60 * 24)
    );
    if (daysActive > p.guaranteeDays) continue;

    const fallbackAssignee = p.candidate.assignedRecruiterId ?? (await managerUserIds())[0];
    if (!fallbackAssignee) continue;

    await prisma.ticket.create({
      data: {
        companyId: p.companyId,
        candidateId: p.candidateId,
        placementId: p.id,
        subject: `Guarantee replacement needed: ${p.candidate.name} at ${p.company.name}`,
        description: `Placement ended ${daysActive} day(s) after start, within the ${p.guaranteeDays}-day guarantee window.`,
        type: "GUARANTEE_REPLACEMENT",
        autoGenerated: true,
        priorityConfirmed: false,
        priority: "HIGH",
        assignedToId: fallbackAssignee,
      },
    });

    await pushNotifications([
      {
        userId: fallbackAssignee,
        type: "FEEDBACK_OVERDUE",
        message: `Guarantee replacement ticket opened for ${p.candidate.name} at ${p.company.name}.`,
        link: `/tickets`,
        entityType: "Placement",
        entityId: p.id,
        dedupeKey: `guarantee-${p.id}`,
      },
    ]);
  }
}

// --- Candidate stuck in stage / new candidate no action ---------------------

async function checkCandidateStageStalls(now: Date) {
  const candidates = await prisma.candidate.findMany({
    where: { stage: { notIn: ["HIRED", "REJECTED"] } },
    include: { role: { include: { company: true } } },
  });

  const notifications: NotificationInput[] = [];
  const msPerDay = 1000 * 60 * 60 * 24;

  for (const c of candidates) {
    if (!c.assignedRecruiterId) continue;
    const daysInStage = Math.floor((now.getTime() - c.stageChangedAt.getTime()) / msPerDay);

    if (c.stage === "APPLIED" && daysInStage >= 3) {
      notifications.push({
        userId: c.assignedRecruiterId,
        type: "NEW_CANDIDATE_NO_ACTION",
        message: `${c.name} has been in Applied for ${daysInStage} days without moving to Screening.`,
        link: `/candidates/${c.id}`,
        entityType: "Candidate",
        entityId: c.id,
        dedupeKey: `applied-noaction-${c.id}`,
      });
    }

    if (daysInStage >= 7) {
      notifications.push({
        userId: c.assignedRecruiterId,
        type: "CANDIDATE_STUCK_IN_STAGE",
        message: `${c.name} (${c.role.company.name}) has been in ${c.stage} for ${daysInStage} days.`,
        link: `/candidates/${c.id}`,
        entityType: "Candidate",
        entityId: c.id,
        dedupeKey: `stuck-${c.id}-${c.stage}`,
      });
    }
  }

  await pushNotifications(notifications);
}

// --- Client gone quiet -------------------------------------------------------

async function checkClientGoneQuiet(now: Date) {
  const companies = await prisma.company.findMany({
    include: {
      activityLogs: { orderBy: { occurredAt: "desc" }, take: 1 },
    },
  });
  const team = await allUserIds();
  const notifications: NotificationInput[] = [];

  for (const company of companies) {
    const lastContact = company.activityLogs[0]?.occurredAt ?? company.createdAt;
    const daysSince = Math.floor((now.getTime() - lastContact.getTime()) / (1000 * 60 * 60 * 24));
    if (daysSince < 60) continue;

    for (const userId of team) {
      notifications.push({
        userId,
        type: "CLIENT_GONE_QUIET",
        message: `${company.name} has gone quiet — ${daysSince} days since last contact.`,
        link: `/companies/${company.id}`,
        entityType: "Company",
        entityId: company.id,
        dedupeKey: `quiet-${company.id}-${lastContact.toISOString()}`,
      });
    }
  }

  await pushNotifications(notifications);
}

// --- Invoices: overdue auto-flip + due-soon / overdue notifications --------

async function checkInvoices(now: Date) {
  const managers = await managerUserIds();
  if (managers.length === 0) return;

  const unpaid = await prisma.invoice.findMany({
    where: { status: { in: ["UNPAID", "OVERDUE"] } },
    include: { company: true },
  });

  const notifications: NotificationInput[] = [];
  const msPerDay = 1000 * 60 * 60 * 24;

  for (const inv of unpaid) {
    const daysUntilDue = Math.ceil((inv.dueDate.getTime() - now.getTime()) / msPerDay);

    if (inv.status === "UNPAID" && daysUntilDue < 0) {
      await prisma.invoice.update({ where: { id: inv.id }, data: { status: "OVERDUE" } });
    }

    if (daysUntilDue <= 5 && daysUntilDue >= 0) {
      for (const userId of managers) {
        notifications.push({
          userId,
          type: "INVOICE_DUE_SOON",
          message: `Invoice for ${inv.company.name} ($${inv.amount}) is due in ${daysUntilDue} day(s).`,
          link: `/invoices`,
          entityType: "Invoice",
          entityId: inv.id,
          dedupeKey: `invoice-due-soon-${inv.id}`,
        });
      }
    }

    if (daysUntilDue < 0) {
      for (const userId of managers) {
        notifications.push({
          userId,
          type: "INVOICE_OVERDUE",
          message: `Invoice for ${inv.company.name} ($${inv.amount}) is overdue.`,
          link: `/invoices`,
          entityType: "Invoice",
          entityId: inv.id,
          dedupeKey: `invoice-overdue-${inv.id}`,
        });
      }
    }
  }

  await pushNotifications(notifications);
}

// --- Lead gone stale ----------------------------------------------------------

async function checkStaleLeads(now: Date) {
  const leads = await prisma.lead.findMany({
    where: { stage: { in: ["CONTACTED", "QUALIFIED"] } },
  });
  const team = await allUserIds();
  const notifications: NotificationInput[] = [];
  const msPerDay = 1000 * 60 * 60 * 24;

  for (const lead of leads) {
    const daysInStage = Math.floor((now.getTime() - lead.stageChangedAt.getTime()) / msPerDay);
    if (daysInStage < 10) continue;
    for (const userId of team) {
      notifications.push({
        userId,
        type: "LEAD_GONE_STALE",
        message: `Lead ${lead.companyName} has been in ${lead.stage} for ${daysInStage} days.`,
        link: `/leads/${lead.id}`,
        entityType: "Lead",
        entityId: lead.id,
        dedupeKey: `lead-stale-${lead.id}-${lead.stage}`,
      });
    }
  }

  await pushNotifications(notifications);
}

// --- Ticket untouched -----------------------------------------------------

async function checkUntouchedTickets(now: Date) {
  const tickets = await prisma.ticket.findMany({
    where: { status: { in: ["OPEN", "IN_PROGRESS"] } },
  });
  const notifications: NotificationInput[] = [];
  const msPerDay = 1000 * 60 * 60 * 24;

  for (const t of tickets) {
    const daysSince = Math.floor((now.getTime() - t.lastActivityAt.getTime()) / msPerDay);
    if (daysSince < 5) continue;
    notifications.push({
      userId: t.assignedToId,
      type: "TICKET_UNTOUCHED",
      message: `Ticket "${t.subject}" has had no update for ${daysSince} days.`,
      link: `/tickets/${t.id}`,
      entityType: "Ticket",
      entityId: t.id,
      dedupeKey: `ticket-untouched-${t.id}-${t.lastActivityAt.toISOString()}`,
    });
  }

  await pushNotifications(notifications);
}

// --- Approval pending -------------------------------------------------------

async function checkPendingApprovals(now: Date) {
  const pending = await prisma.approvalRequest.findMany({
    where: { status: "PENDING" },
    include: { candidate: { include: { role: { include: { company: true } } } } },
  });
  const team = await allUserIds();
  const notifications: NotificationInput[] = [];

  for (const req of pending) {
    if (businessDaysBetween(req.createdAt, now) < 1) continue;
    for (const userId of team) {
      if (userId === req.requestedById) continue;
      notifications.push({
        userId,
        type: "APPROVAL_PENDING",
        message: `Approval still pending for ${req.candidate.name} at ${req.candidate.role.company.name}.`,
        link: `/candidates/${req.candidate.id}`,
        entityType: "ApprovalRequest",
        entityId: req.id,
        dedupeKey: `approval-pending-${req.id}`,
      });
    }
  }

  await pushNotifications(notifications);
}

let lastRunAt = 0;
const MIN_INTERVAL_MS = 60_000;

/**
 * Evaluates every §9 automation trigger and creates any missing tickets /
 * notifications. There's no standing worker process in this environment, so
 * this is invoked opportunistically (see /api/notifications) and throttled
 * to at most once a minute per server process. Wire this to a real scheduler
 * (e.g. Vercel Cron hitting /api/cron/evaluate) in production.
 */
export async function runAutomationSweep(force = false) {
  const now = Date.now();
  if (!force && now - lastRunAt < MIN_INTERVAL_MS) return;
  lastRunAt = now;

  const nowDate = new Date();
  await Promise.all([
    checkFeedbackOverdue(nowDate),
    checkGuaranteeTriggers(),
    checkCandidateStageStalls(nowDate),
    checkClientGoneQuiet(nowDate),
    checkInvoices(nowDate),
    checkStaleLeads(nowDate),
    checkUntouchedTickets(nowDate),
    checkPendingApprovals(nowDate),
  ]);
}
