import Link from "next/link";
import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { TICKET_TYPE_LABELS } from "@/lib/ticket-defaults";
import { TicketControls } from "@/components/TicketControls";
import { TicketUpdates } from "@/components/TicketUpdates";

export default async function TicketDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const [ticket, users] = await Promise.all([
    prisma.ticket.findUnique({
      where: { id },
      include: {
        company: true,
        candidate: true,
        assignedTo: { select: { id: true, name: true } },
        createdBy: { select: { name: true } },
        updates: { orderBy: { createdAt: "desc" }, include: { author: { select: { name: true } } } },
      },
    }),
    prisma.user.findMany({ orderBy: { name: "asc" }, select: { id: true, name: true } }),
  ]);
  if (!ticket) notFound();

  return (
    <div className="max-w-2xl space-y-6">
      <div>
        <p className="text-sm text-slate-400">
          <Link href={`/companies/${ticket.company.id}`} className="hover:underline">
            {ticket.company.name}
          </Link>
          {ticket.candidate && (
            <>
              {" "}
              /{" "}
              <Link href={`/candidates/${ticket.candidate.id}`} className="hover:underline">
                {ticket.candidate.name}
              </Link>
            </>
          )}
        </p>
        <h1 className="text-xl font-semibold text-slate-900">{ticket.subject}</h1>
        <p className="text-sm text-slate-500">
          {TICKET_TYPE_LABELS[ticket.type]} · {ticket.autoGenerated ? "Auto-generated" : `Created by ${ticket.createdBy?.name ?? "—"}`}{" "}
          · {new Date(ticket.createdAt).toLocaleString()}
        </p>
      </div>

      {ticket.description && (
        <div className="bg-white border border-slate-200 rounded-lg p-4">
          <p className="text-sm text-slate-700 whitespace-pre-wrap">{ticket.description}</p>
        </div>
      )}

      <div className="bg-white border border-slate-200 rounded-lg p-4">
        <TicketControls
          ticketId={ticket.id}
          status={ticket.status}
          priority={ticket.priority}
          assignedToId={ticket.assignedTo.id}
          priorityConfirmed={ticket.priorityConfirmed}
          autoGenerated={ticket.autoGenerated}
          users={users}
        />
      </div>

      <div className="bg-white border border-slate-200 rounded-lg p-4">
        <h2 className="text-sm font-semibold text-slate-900 mb-2">Updates</h2>
        <TicketUpdates
          ticketId={ticket.id}
          updates={ticket.updates.map((u) => ({
            id: u.id,
            body: u.body,
            createdAt: u.createdAt.toISOString(),
            author: u.author,
          }))}
        />
      </div>
    </div>
  );
}
