import { NextResponse } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { requireUser } from "@/lib/permissions";
import { withApiErrors } from "@/lib/api-utils";

const createSchema = z.object({
  companyId: z.string().min(1),
  candidateId: z.string().optional(),
  subject: z.string().min(1),
  description: z.string().optional(),
  type: z.enum([
    "CLIENT_SWAP_REQUEST",
    "CANDIDATE_QUALITY_COMPLAINT",
    "INVOICE_BILLING_DISPUTE",
    "URGENT_ADHOC_REQUEST",
    "CONTRACT_TERMS_QUESTION",
    "CANDIDATE_CONSENT_DATA_ISSUE",
    "OTHER",
  ]),
  priority: z.enum(["LOW", "MEDIUM", "HIGH"]),
  assignedToId: z.string().min(1),
});

export const GET = withApiErrors(async (req: Request) => {
  const user = await requireUser();
  const { searchParams } = new URL(req.url);
  const status = searchParams.get("status");
  const mine = searchParams.get("mine");

  const tickets = await prisma.ticket.findMany({
    where: {
      ...(status ? { status: status as never } : {}),
      ...(mine ? { assignedToId: user.id } : {}),
    },
    orderBy: [{ priority: "desc" }, { createdAt: "desc" }],
    include: { company: true, assignedTo: { select: { name: true } }, candidate: { select: { name: true } } },
  });

  return NextResponse.json({ tickets });
});

// Manual ticket creation (§6) — always a person clicking "New Ticket" after a call/email.
export const POST = withApiErrors(async (req: Request) => {
  const user = await requireUser();
  const data = createSchema.parse(await req.json());

  const ticket = await prisma.ticket.create({
    data: {
      companyId: data.companyId,
      candidateId: data.candidateId,
      subject: data.subject,
      description: data.description,
      type: data.type,
      priority: data.priority,
      assignedToId: data.assignedToId,
      createdById: user.id,
      autoGenerated: false,
      priorityConfirmed: true,
    },
  });

  return NextResponse.json({ ticket }, { status: 201 });
});
