"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

type User = { id: string; name: string };

export function TicketControls({
  ticketId,
  status,
  priority,
  assignedToId,
  priorityConfirmed,
  autoGenerated,
  users,
}: {
  ticketId: string;
  status: string;
  priority: string;
  assignedToId: string;
  priorityConfirmed: boolean;
  autoGenerated: boolean;
  users: User[];
}) {
  const router = useRouter();
  const [busy, setBusy] = useState(false);
  const [localPriority, setLocalPriority] = useState(priority);

  async function patch(body: Record<string, unknown>) {
    setBusy(true);
    try {
      await fetch(`/api/tickets/${ticketId}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      });
      router.refresh();
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="space-y-3">
      {autoGenerated && !priorityConfirmed && (
        <div className="text-sm text-amber-700 bg-amber-50 border border-amber-200 rounded-md p-3">
          <p className="font-medium">This ticket was auto-generated — confirm its priority.</p>
          <p className="text-xs mt-1 mb-2">
            Auto-generated tickets don&apos;t get a silent, unconfirmed priority — the assignee needs to set it.
          </p>
          <div className="flex items-center gap-2">
            <select
              value={localPriority}
              onChange={(e) => setLocalPriority(e.target.value)}
              className="rounded border border-amber-300 px-2 py-1 text-sm bg-white"
            >
              <option value="LOW">Low</option>
              <option value="MEDIUM">Medium</option>
              <option value="HIGH">High</option>
            </select>
            <button
              disabled={busy}
              onClick={() => patch({ priority: localPriority, confirmPriority: true })}
              className="rounded-md bg-slate-900 text-white text-xs font-medium px-3 py-1.5 hover:bg-slate-800 disabled:opacity-60"
            >
              Confirm priority
            </button>
          </div>
        </div>
      )}

      <div className="flex flex-wrap gap-3">
        <div>
          <label className="block text-xs font-medium text-slate-500 mb-1">Status</label>
          <select
            value={status}
            disabled={busy}
            onChange={(e) => patch({ status: e.target.value })}
            className="rounded-md border border-slate-300 px-2 py-1.5 text-sm"
          >
            <option value="OPEN">Open</option>
            <option value="IN_PROGRESS">In progress</option>
            <option value="RESOLVED">Resolved</option>
            <option value="CLOSED">Closed</option>
          </select>
        </div>
        <div>
          <label className="block text-xs font-medium text-slate-500 mb-1">Priority</label>
          <select
            value={priority}
            disabled={busy}
            onChange={(e) => patch({ priority: e.target.value })}
            className="rounded-md border border-slate-300 px-2 py-1.5 text-sm"
          >
            <option value="LOW">Low</option>
            <option value="MEDIUM">Medium</option>
            <option value="HIGH">High</option>
          </select>
        </div>
        <div>
          <label className="block text-xs font-medium text-slate-500 mb-1">Assigned to</label>
          <select
            value={assignedToId}
            disabled={busy}
            onChange={(e) => patch({ assignedToId: e.target.value })}
            className="rounded-md border border-slate-300 px-2 py-1.5 text-sm"
          >
            {users.map((u) => (
              <option key={u.id} value={u.id}>
                {u.name}
              </option>
            ))}
          </select>
        </div>
      </div>
    </div>
  );
}
